clear all;
close all;
clc;
I=imread('image2.jpg');
I11=rgb2gray(I);
I1=imtophat(I11,strel('disk',10));
figure,subplot(3,3,1),imshow(I1);
I2=imadjust(I1);
subplot(3,3,2),imshow(I2);
level=graythresh(I2);
BW=im2bw(I2,level);
subplot(3,3,3),imshow(BW);
c=~BW;
subplot(3,3,4),imshow(c);
D=-bwdist(c);
D(c)=-Inf;
L=watershed(D);
subplot(3,3,5),imshow(L);
Wi=label2rgb(L,'hot','W');
subplot(3,3,6),imshow(Wi);
im=I;
im(L==0)=0;
subplot(3,3,7),imshow(im);